module3/intro/config/routes.rb
Rails.application.routes.draw do
  resources :items
  
  # get 'items/index'
  # get 'items/show'
  # get 'items/new'
  # get 'items/edit'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

module3/intro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

module3/intro/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    render :index
  end

  def show
    # where can I find @items?
    @item = Item.find(params[:id])
    render :show
  end

  def new
    @item = Item.new
    render :new
  end

  def create
    item = Item.create(params.require(:item).permit(:name, :price))
    redirect_to items_path, :notice => "Item berhasil ditambahkan ✅"
  end

  def edit
    @item = Item.find(params[:id])
    render :edit
  end

  def update
    @item = Item.find(params[:id])

    if @item.update(params.require(:item).permit(:name, :price))
      redirect_to items_path, :notice => "Item berhasil diperbarui ✅"
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path, :notice => "Item berhasil dihapus ✅"
  end
end

module3/intro/app/views/items/edit.html.erb
<h1>Edit <%= @item.name %> </h1>

<%= form_with model: @item do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.submit %>
<% end %>

<p><%= link_to "Back", items_path %></p>

module3/intro/app/views/items/index.html.erb
<h1> Items </h1>
<% if @items.any? %>
<table>
  <thead>
    <tr>
        <td><b>Name</b></td>
        <td><b>Price</b></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.price %></td>
        <td><%= link_to "Show", item_path(item) %></td>
        <td><%= link_to "Edit", edit_item_path(item) %></td>
        <td><%= button_to "Delete", item, :confirm => "Yakin ingin menghapus item ini?", :method => :delete %></td>
    <% end %>
      </tr>
  </tbody>
</table>
<% else %>
  <p>Item kosong</p>
<% end %>
  
<a href="/items/new">New Item</a>

module3/intro/app/views/items/new.html.erb
<h3>Create an Item</h3>

<%= form_with model: @item do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :price, placeholder: "price" %>
  <%= form.submit %>
<% end %>

<p><%= link_to "Back", items_path %></p>
  

module3/intro/app/views/items/show.html.erb
<h1>Item Detail</h1>
<p>Item name: <%= @item.name %> </p>
<p>Item price: <%= @item.price %> </p>

<p><%= link_to "Back", items_path %></p>